name: Luttrell Family Blog
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.204453558428213
color:
  saturation: 0.3408963
  brandStrength: 0.3886474424507469
  rhythmicContrast: 0.8867149
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.4656284
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
typography_spectrum: 0.5
analytics:
  twitter: null
  google: null
  facebook: null
