name: Luttrell Family Blog
favicon: null
layout_spectrum: 0.204453558428213
typography_spectrum: 0.08861437
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Luttrell Family Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3635875
  lightness: 0.4656284
  saturation: 0.3408963
  rhythmicContrast: 0.8867149
purpose: []
